[package]
name = "builder-node"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "reproductive-nix-cache-builder-node"
path = "src/main.rs"

[dependencies]
builder-core = { path = "../builder-core" }
shared = { path = "../shared" }
anyhow.workspace = true
axum = "0.8.9"
clap.workspace = true
serde.workspace = true
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true
tower = { version = "0.5", features = ["util"] }
