[package]
name = "server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "reproductive-nix-cache-server"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }
clap.workspace = true
anyhow.workspace = true
base64.workspace = true
axum = "0.8.9"
chrono.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true
nix-base32 = "0.2"
object_store = { version = "0.14.1", features = ["aws"] }
sea-orm = { version = "1.1.20", default-features = false, features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-sqlite",
    "with-chrono",
] }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
